sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "7"

script: npm run travis

# not until I fix the coffee-coverage issue: it doesn't allow excluding files.
# i'm using a custom version locally which allows that and more.
# so, i'll publish coverage locally for now.
# after_success:
#  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
